name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --settings ./.mvn/unblock-mirrors.xml --file pom.xml 
    - name: Copy artifacts
      run: mkdir staging && cp target/*.jar staging  && cp target/*.zip staging
    - name: Package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: staging
    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests # optional
        name: codecov-umbrella # optional
    
    - name: Get Current Release
      if: ${{ github.event_name == 'release' }}
      id: get_current_release
      uses: joutvhu/get-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact and release
      if: ${{ github.event_name == 'release' }}
      uses: nanoufo/action-upload-artifacts-and-release-assets@v1.4
      with:
        path: |
          staging/*.zip
        upload-release-files: true
        release-upload-url: ${{ steps.get_current_release.outputs.upload_url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
