
name: quay.io push

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: medbioinf/pia
        labels: |
          org.opencontainers.image.title=PIA
          org.opencontainers.image.description=PIA - Protein Inference Algorithms
      
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: pia
        tags: latest ${{ github.sha }} ${{ steps.meta.outputs.tags }}
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/medbioinf
        username: ${{ secrets.QUAY_ROBOT_ID }}
        password: ${{ secrets.QUAY_ROBOT_PW }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
